"""
convolutionalfixedsum-tests
***************************

:copyright: David Griffin <dgdguk@gmail.com> (2024)
:license:  BSD-3-Clause license

This module contains all tests for ConvolutionalFixedSum. These are primarily large statistical tests
and therefore they are not integrated with an automatic unit test framework, as some can take a rather
long time to complete.

In addition, the code used to create figures for the paper:

"ConvolutionalFixedSum: Uniformly Generating Random Values with a Fixed Sum Subject to Arbitrary Constraints",
(David Griffin and Rob Davis, published at RTAS 2025)

is included in this module. For example, Figure 3 from that paper can be generated by running

python -m tests.figure_3
"""